package crypto

import (
	"crypto/aes"
	"crypto/cipher"
	"crypto/rand"
	"encoding/hex"
	"errors"
	"fmt"
	"io"
	"os"
	"strings"
)

const (
	// DefaultKeyID is the default key ID stored in credentials.enc_key_id
	DefaultKeyID = "master-v1"

	dekSize   = 32 // 256-bit AES DEK
	nonceSize = 12 // Standard 96-bit GCM nonce
)

// LoadMasterKey reads and validates the master encryption key from the given path.
// It accepts either 32 raw bytes or a 64-character hex-encoded string (generated by setup.sh).
func LoadMasterKey(path string) ([]byte, error) {
	if strings.TrimSpace(path) == "" {
		return nil, errors.New("crypto: master key path is empty")
	}

	data, err := os.ReadFile(path)
	if err != nil {
		if os.IsNotExist(err) {
			return nil, fmt.Errorf("crypto: master key file %q does not exist; check /etc/dash/master.key or config", path)
		}
		return nil, fmt.Errorf("crypto: failed to read master key file %q: %w", path, err)
	}

	trimmed := strings.TrimSpace(string(data))
	// Check if hex encoded 32 bytes (64 hex characters)
	if len(trimmed) == 64 {
		decoded, err := hex.DecodeString(trimmed)
		if err == nil && len(decoded) == 32 {
			return decoded, nil
		}
	}

	// Check if raw 32 bytes
	if len(data) == 32 {
		return data, nil
	}

	return nil, fmt.Errorf("crypto: master key in %q must be 32 raw bytes or 64 hex characters, got %d bytes", path, len(data))
}

// EncryptedData holds the envelope-encrypted payload and metadata.
type EncryptedData struct {
	Payload []byte
	KeyID   string
	Nonce   string // Hex-encoded (24 bytes: 12-byte KEK nonce + 12-byte DEK nonce = 48 hex chars)
}

// EncryptEnvelope performs envelope encryption:
// 1. Generates a random 256-bit DEK (Data Encryption Key).
// 2. Encrypts plaintext with DEK using AES-256-GCM.
// 3. Encrypts DEK with masterKey using AES-256-GCM.
// 4. Returns combined encrypted DEK + ciphertext in Payload, with hex-encoded nonces.
func EncryptEnvelope(masterKey []byte, plaintext []byte) (*EncryptedData, error) {
	if len(masterKey) != 32 {
		return nil, fmt.Errorf("crypto: invalid master key length: expected 32 bytes, got %d", len(masterKey))
	}

	// 1. Generate random DEK
	dek := make([]byte, dekSize)
	if _, err := io.ReadFull(rand.Reader, dek); err != nil {
		return nil, fmt.Errorf("crypto: failed to generate DEK: %w", err)
	}

	// 2. Encrypt plaintext with DEK
	dekBlock, err := aes.NewCipher(dek)
	if err != nil {
		return nil, fmt.Errorf("crypto: failed to init DEK cipher: %w", err)
	}
	dekGCM, err := cipher.NewGCM(dekBlock)
	if err != nil {
		return nil, fmt.Errorf("crypto: failed to init DEK GCM: %w", err)
	}

	dekNonce := make([]byte, nonceSize)
	if _, err := io.ReadFull(rand.Reader, dekNonce); err != nil {
		return nil, fmt.Errorf("crypto: failed to generate DEK nonce: %w", err)
	}
	encryptedPlaintext := dekGCM.Seal(nil, dekNonce, plaintext, nil)

	// 3. Encrypt DEK with masterKey
	kekBlock, err := aes.NewCipher(masterKey)
	if err != nil {
		return nil, fmt.Errorf("crypto: failed to init KEK cipher: %w", err)
	}
	kekGCM, err := cipher.NewGCM(kekBlock)
	if err != nil {
		return nil, fmt.Errorf("crypto: failed to init KEK GCM: %w", err)
	}

	kekNonce := make([]byte, nonceSize)
	if _, err := io.ReadFull(rand.Reader, kekNonce); err != nil {
		return nil, fmt.Errorf("crypto: failed to generate KEK nonce: %w", err)
	}
	encryptedDEK := kekGCM.Seal(nil, kekNonce, dek, nil)

	// Combined payload: [len(encryptedDEK): 2 bytes][encryptedDEK][encryptedPlaintext]
	encDEKLen := len(encryptedDEK)
	combined := make([]byte, 2+encDEKLen+len(encryptedPlaintext))
	combined[0] = byte(encDEKLen >> 8)
	combined[1] = byte(encDEKLen & 0xff)
	copy(combined[2:2+encDEKLen], encryptedDEK)
	copy(combined[2+encDEKLen:], encryptedPlaintext)

	// Combined nonce: kekNonce (12) + dekNonce (12) = 24 bytes
	combinedNonces := append(kekNonce, dekNonce...)

	return &EncryptedData{
		Payload: combined,
		KeyID:   DefaultKeyID,
		Nonce:   hex.EncodeToString(combinedNonces),
	}, nil
}

// DecryptEnvelope decrypts an envelope-encrypted payload using the master key.
func DecryptEnvelope(masterKey []byte, encPayload []byte, keyID string, nonceHex string) ([]byte, error) {
	if len(masterKey) != 32 {
		return nil, fmt.Errorf("crypto: invalid master key length: expected 32 bytes, got %d", len(masterKey))
	}
	if len(encPayload) < 2 {
		return nil, errors.New("crypto: invalid payload: too short")
	}

	nonces, err := hex.DecodeString(nonceHex)
	if err != nil || len(nonces) != nonceSize*2 {
		return nil, fmt.Errorf("crypto: invalid nonce: %w", err)
	}
	kekNonce := nonces[:nonceSize]
	dekNonce := nonces[nonceSize:]

	encDEKLen := int(encPayload[0])<<8 | int(encPayload[1])
	if encDEKLen <= 0 || 2+encDEKLen > len(encPayload) {
		return nil, errors.New("crypto: invalid DEK length in payload")
	}

	encryptedDEK := encPayload[2 : 2+encDEKLen]
	encryptedPlaintext := encPayload[2+encDEKLen:]

	// 1. Decrypt DEK with masterKey
	kekBlock, err := aes.NewCipher(masterKey)
	if err != nil {
		return nil, fmt.Errorf("crypto: failed to init KEK cipher: %w", err)
	}
	kekGCM, err := cipher.NewGCM(kekBlock)
	if err != nil {
		return nil, fmt.Errorf("crypto: failed to init KEK GCM: %w", err)
	}

	dek, err := kekGCM.Open(nil, kekNonce, encryptedDEK, nil)
	if err != nil {
		return nil, fmt.Errorf("crypto: failed to decrypt DEK (master key mismatch?): %w", err)
	}

	// 2. Decrypt plaintext with DEK
	dekBlock, err := aes.NewCipher(dek)
	if err != nil {
		return nil, fmt.Errorf("crypto: failed to init DEK cipher: %w", err)
	}
	dekGCM, err := cipher.NewGCM(dekBlock)
	if err != nil {
		return nil, fmt.Errorf("crypto: failed to init DEK GCM: %w", err)
	}

	plaintext, err := dekGCM.Open(nil, dekNonce, encryptedPlaintext, nil)
	if err != nil {
		return nil, fmt.Errorf("crypto: failed to decrypt ciphertext: %w", err)
	}

	return plaintext, nil
}
